# Generated by Django 5.0 on 2026-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDeMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='Escribe aquí tu información personal...', help_text='Contenido de la página Acerca de Mí')),
            ],
            options={
                'verbose_name': 'Acerca de Mí',
                'verbose_name_plural': 'Acerca de Mí',
            },
        ),
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_especial', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('bonificacion', models.CharField(max_length=150)),
                ('fortaleza', models.CharField(max_length=100)),
                ('debilidades', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='estretegias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='naval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
                ('no_unidades', models.IntegerField()),
                ('civilizacion', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
