# Generated by Django 5.0 on 2026-01-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('victoria', 'Victoria'), ('derrota', 'Derrota'), ('empate', 'Empate')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('civilizacion_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_jugador', to='biblioteca.culturas')),
                ('civilizacion_rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_rival', to='biblioteca.culturas')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batalla',
                'verbose_name_plural': 'Batallas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
